#!/usr/bin/env bash
set -euo pipefail

# TEL22_IBI matched A/B control using the exact shared checkpoint generated by
# 06_test_nve_scaling_and_drift.sh. PaiNN remains disabled, so changing
# --ml_precision from float32 to float64 MUST NOT change the active Hamiltonian.
# This script therefore validates conservative-path invariance rather than an
# actual FP32-vs-FP64 force-kernel precision effect.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "${SCRIPT_DIR}/model_config.sh" ]]; then
    TUTORIAL_DIR="${SCRIPT_DIR}"
elif [[ -f "${SCRIPT_DIR}/../../model_config.sh" ]]; then
    TUTORIAL_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
else
    echo "[ERROR] Cannot locate tutorials/tel22_IBI from ${SCRIPT_DIR}" >&2
    exit 1
fi
FRAMEWORK_ROOT="$(cd "${TUTORIAL_DIR}/../.." && pwd)"
CERTIFIER="${FRAMEWORK_ROOT}/simulation/certify_nve.py"
PYTHON_BIN="${PYTHON_BIN:-python3}"

if [[ -x "${FRAMEWORK_ROOT}/espresso/build/pypresso" ]]; then
    DEFAULT_PYPRESSO="${FRAMEWORK_ROOT}/espresso/build/pypresso"
else
    DEFAULT_PYPRESSO="pypresso"
fi
PYPRESSO="${PYPRESSO:-${DEFAULT_PYPRESSO}}"

cd "${TUTORIAL_DIR}"
source ./model_config.sh
load_model_dependent_config step34

MODEL="${IBI_MODEL}"
CONFIG="${IBI_PROMOTION_CONFIG}"
DATASET="${IBI_PROMOTION_DATASET}"
RB_INFO="${IBI_PROMOTION_RB_INFO}"
PRIORS="${IBI_PROMOTION_CURRENT_DIR}/cg_priors.json"

NVE_DEVICE="cpu"
NVE_ML_PRECISION="float64"
NVE_NEIGHBOR_SEARCH="${NVE_NEIGHBOR_SEARCH:-${IBI_PROMOTION_NEIGHBOR_SEARCH}}"
NVE_DTS="${NVE_DTS:-0.001 0.0015 0.002 0.003 0.004 0.005}"
NVE_DURATION_PS="${NVE_DURATION_PS:-2.0}"
NVE_OUTPUT_DIR="${NVE_OUTPUT_DIR:-diagnostics/nve/nve_scaling_drift_recheck_promoted_ibi_fp64}"
NVE_SLOPE_MIN="${NVE_SLOPE_MIN:-1.8}"
NVE_SLOPE_MAX="${NVE_SLOPE_MAX:-2.2}"
NVE_MIN_R2="${NVE_MIN_R2:-0.95}"
NVE_MAX_RELATIVE_DRIFT="${NVE_MAX_RELATIVE_DRIFT:-2e-5}"

PREP_DIR="${NVE_PREP_DIR:-diagnostics/nve/nve_scaling_drift_recheck_promoted_ibi_shared_nvt}"
PREP_CHECKPOINT="${PREP_DIR}/equilibrated_promoted_ibi_recheck.npz"
FP32_REPORT="${FP32_REPORT:-diagnostics/nve/nve_scaling_drift_recheck_promoted_ibi_fp32/nve_certification_report.json}"

usage() {
    cat <<'USAGE'
Usage:
  06b_test_nve_scaling_and_drift_fp64.sh [--dry-run | --overwrite | --resume]

Matched TEL22_IBI conservative-only control. Run 06_test_nve_scaling_and_drift.sh
first: this script deliberately reuses its exact NVT checkpoint.

Because PaiNN is disabled, --ml_precision=float64 is an inactive setting.
FP32-labelled and FP64-labelled conservative results should therefore agree.
USAGE
}

MODE="normal"
case "${1:-}" in
    "") ;;
    --dry-run) MODE="dry-run"; shift ;;
    --overwrite) MODE="overwrite"; shift ;;
    --resume) MODE="resume"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "[ERROR] Unknown option: $1" >&2; usage >&2; exit 2 ;;
esac
if (($# != 0)); then
    echo "[ERROR] Unexpected extra arguments: $*" >&2
    exit 2
fi

for path in "${MODEL}" "${MODEL}.manifest.json" "${CONFIG}" "${DATASET}" "${RB_INFO}" "${PRIORS}"; do
    [[ -f "${path}" ]] || { echo "[ERROR] Missing required IBI input: ${path}" >&2; exit 1; }
done
[[ -f "${CERTIFIER}" ]] || { echo "[ERROR] Missing certifier: ${CERTIFIER}" >&2; exit 1; }

SOURCE_CHECKPOINT=""
for candidate in \
    "${IBI_PROMOTION_SOURCE_CHECKPOINT}" \
    diagnostics/ml/postibi_runtime_validation/equilibrated_postibi.npz \
    equilibrated.npz; do
    if [[ -f "${candidate}" ]]; then
        SOURCE_CHECKPOINT="${candidate}"
        break
    fi
done
[[ -n "${SOURCE_CHECKPOINT}" ]] || {
    echo "[ERROR] No source checkpoint found." >&2
    exit 1
}

read -r -a DT_ARGS <<< "${NVE_DTS}"
((${#DT_ARGS[@]} >= 3)) || { echo "[ERROR] NVE_DTS needs at least three values" >&2; exit 1; }

cat <<EOF_PLAN
[TEL22_IBI CONSERVATIVE NVE MATCHED CONTROL -- FP64 LABEL]
reference         : 06 FP32-labelled conservative recheck
changed setting   : ml_precision float32 -> float64 (PaiNN remains OFF)
active Hamiltonian: promoted conservative IBI only
priors            : ${PRIORS}
model provenance  : ${MODEL}
shared checkpoint : ${PREP_CHECKPOINT}
dt grid [ps]      : ${NVE_DTS}
duration / dt     : ${NVE_DURATION_PS} ps
sampling          : every integration step
thermostat NVE    : OFF
device            : ${NVE_DEVICE}
ML precision flag : ${NVE_ML_PRECISION} (inactive)
neighbor search   : ${NVE_NEIGHBOR_SEARCH}
output            : ${NVE_OUTPUT_DIR}
EOF_PLAN

if [[ ! -s "${PREP_CHECKPOINT}" ]]; then
    echo "[ERROR] Missing shared checkpoint: ${PREP_CHECKPOINT}" >&2
    echo "        Run diagnostics/scripts/06_test_nve_scaling_and_drift.sh --overwrite first." >&2
    exit 1
fi

if [[ "${MODE}" == "dry-run" ]]; then
    for dt in "${DT_ARGS[@]}"; do
        echo "[PLAN] NVE dt=${dt} ps duration=${NVE_DURATION_PS} ps"
    done
    exit 0
fi

CERT_CMD=(
    "${PYTHON_BIN}" "${CERTIFIER}"
    --pypresso "${PYPRESSO}"
    --model "${MODEL}"
    --disable-ml
    --config "${CONFIG}"
    --priors "${PRIORS}"
    --rb-info "${RB_INFO}"
    --dataset "${DATASET}"
    --checkpoint "${PREP_CHECKPOINT}"
    --require-checkpoint-hamiltonian-mode conservative_classical_model_provenance_ml_disabled
    --require-checkpoint-source "${SOURCE_CHECKPOINT}"
    --dts "${DT_ARGS[@]}"
    --duration-ps "${NVE_DURATION_PS}"
    --device "${NVE_DEVICE}"
    --ml-precision "${NVE_ML_PRECISION}"
    --neighbor-search "${NVE_NEIGHBOR_SEARCH}"
    --output-dir "${NVE_OUTPUT_DIR}"
    --slope-min "${NVE_SLOPE_MIN}"
    --slope-max "${NVE_SLOPE_MAX}"
    --min-r2 "${NVE_MIN_R2}"
    --max-relative-drift "${NVE_MAX_RELATIVE_DRIFT}"
)
if [[ "${MODE}" == "resume" ]]; then
    CERT_CMD+=(--reuse-existing)
elif [[ "${MODE}" == "overwrite" ]]; then
    CERT_CMD+=(--overwrite)
fi
"${CERT_CMD[@]}"

REPORT="${NVE_OUTPUT_DIR}/nve_certification_report.json"
[[ -f "${REPORT}" ]] || { echo "[ERROR] Missing report: ${REPORT}" >&2; exit 1; }

"${PYTHON_BIN}" - "${REPORT}" "${FP32_REPORT}" <<'PY'
import json, math, pathlib, sys
p64 = pathlib.Path(sys.argv[1])
p32 = pathlib.Path(sys.argv[2])
r64 = json.load(p64.open(encoding="utf-8"))
c = r64["certification"]
s = c["scaling"]
runs64 = sorted(r64["runs"], key=lambda x: float(x["dt_ps"]))
print("\n[TEL22_IBI CONSERVATIVE NVE MATCHED CONTROL SUMMARY -- FP64 LABEL]")
print(f"[SCALING] p={float(s['exponent_p']):.6f} R2={float(s['loglog_r2']):.6f} pass={c['scaling_pass']}")
worst = max(runs64, key=lambda x: float(x["relative_block_mean_drift"]))
print(f"[DRIFT] max={float(worst['relative_block_mean_drift']):.3e} at dt={float(worst['dt_ps']):g} ps pass={c['drift_pass']}")
print("[TABLE] dt_ps       sigma_E       sigma_E/dt^2    rel_block_drift")
c2=[]
for x in runs64:
    dt=float(x["dt_ps"]); sig=float(x["sigma_E"]); drift=float(x["relative_block_mean_drift"])
    val=sig/(dt*dt); c2.append(val)
    print(f"        {dt:<10g} {sig:<13.6g} {val:<15.6g} {drift:.3e}")
pos=[x for x in c2 if x>0 and math.isfinite(x)]
if pos:
    print(f"[C2] max/min spread={max(pos)/min(pos):.3f}")
print(f"[FINAL] pass={c['pass']}")

if p32.is_file():
    r32 = json.load(p32.open(encoding="utf-8"))
    runs32 = {float(x["dt_ps"]): x for x in r32["runs"]}
    abs_diffs=[]; rel_diffs=[]; drift_diffs=[]
    for x in runs64:
        dt=float(x["dt_ps"])
        if dt not in runs32:
            continue
        a=float(runs32[dt]["sigma_E"]); b=float(x["sigma_E"])
        d=abs(a-b); abs_diffs.append(d)
        rel_diffs.append(d/max(abs(a),abs(b),1e-300))
        da=float(runs32[dt]["relative_block_mean_drift"])
        db=float(x["relative_block_mean_drift"])
        drift_diffs.append(abs(da-db))
    if abs_diffs:
        print(f"[A/B] max |delta sigma_E|={max(abs_diffs):.3e} max relative={max(rel_diffs):.3e}")
        print(f"[A/B] max |delta drift|={max(drift_diffs):.3e}")
        print("[A/B NOTE] PaiNN is OFF: equality is expected because ml_precision is inactive.")
else:
    print(f"[A/B NOTE] FP32 report not found at {p32}; numerical comparison skipped.")
print(f"[REPORT] {p64}")
PY
